[libdefaults]
    default_realm = HTLWYDEV.AT
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    forwardable = true
    rdns = false

[realms]
    HTLWYDEV.AT = {
        kdc = dc01.htlwydev.at
        admin_server = dc01.htlwydev.at
    }

[domain_realm]
    .htlwydev.at = HTLWYDEV.AT
    htlwydev.at = HTLWYDEV.AT
