network:
  version: 2
  ethernets:
    ens33:
      addresses:
        - 10.10.10.20/24
      nameservers:
        addresses:
          - 10.10.10.10
          - 1.1.1.1
          - 8.8.8.8
        search:
          - htlwydev.at
    ens37:
      dhcp4: true
      dhcp6: false
